export const LOTTERY_INITIAL_SPEED_MS = 50
export const LOTTERY_SPEED_INCREMENT_MS = 5
export const LOTTERY_MAX_SPEED_MS = 300
export const LOTTERY_ANIMATION_DURATION_MS = 4000
export const LOTTERY_RESULT_DELAY_MS = 500
